[package]
name = "sig_ast"
version = "0.1.0"
edition = "2021"

[dependencies]
peg = "0.8.2"
thiserror = "1.0.58"
smallvec = "1.13.2"
wasm-encoder = "0.206.0"
clap = { version = "4.5.4", features = ["derive"] }
